## Transformación y limpieza

### Índice
1. Importación de librerías 
2. Carga de datos
3. Unión de hojas de customer-details
4. Inspección inicial de bank-additional
5. Limpieza y transformación de bank-additional
6. Inspección inicial de customer-details
7. Limpieza y transformación de customer-details
8. Guardado del dataset limpio

----------------------------------------------------------

1. Importación de librerias

In [1]:
# Importamos las librerías usadas 
import pandas as pd
import numpy as np
import sidetable as stb

-----------------------

2. Carga de datos

In [2]:
# Leemos el csv "bank_additional"
df_bank_additional = pd.read_csv("C:/Users/patri/OneDrive/Documentos/Proyecto-EDA/data/raw/bank-additional.csv")
df_bank_additional.head(5)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,...,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,...,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,...,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,...,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,...,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [3]:
# Leemos las últimas 5 líneas 
df_bank_additional.tail()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
42995,19154,NaN,admin.,MARRIED,university.degree,0.0,0.0,0.0,cellular,618,...,1.4,"93,444","-36,1",NaN,"5228,1",yes,13-octubre-2015,38.147,-105.582,4eed05de-2a98-4227-b488-32122009b638
42996,26206,34.0,technician,MARRIED,professional.course,0.0,1.0,1.0,cellular,42,...,-0.1,"93,2",-42,NaN,"5195,8",no,17-marzo-2018,49.235,-112.201,0f0aca88-4088-4fe2-905f-44fb675d9493
42997,15046,NaN,blue-collar,SINGLE,basic.6y,0.0,1.0,0.0,cellular,391,...,1.4,"93,918","-42,7",NaN,"5228,1",no,15-septiembre-2016,40.679,-120.015,cadadd4b-7ee5-4019-b13a-ca01bb67ca5b
42998,15280,NaN,admin.,MARRIED,university.degree,NaN,0.0,0.0,cellular,674,...,1.4,"93,918","-42,7","4,958","5228,1",no,23-septiembre-2019,27.772,-117.518,5f432048-d515-4bb5-9c94-62db451f88d4
42999,27570,NaN,unemployed,SINGLE,university.degree,0.0,0.0,1.0,cellular,104,...,-0.1,"93,2",-42,"4,021","5195,8",no,6-noviembre-2019,41.146,-105.026,993bbbd6-4dbc-4a40-a408-f91f8462bee6

In [4]:
excel_customer_datails = pd.ExcelFile("C:/Users/patri/OneDrive/Documentos/Proyecto-EDA/data/raw/customer-details.xlsx")
excel_customer_datails.sheet_names

['2012', '2013', '2014']

In [5]:
# leemos la primera página del libro excel "customer-datails"
df_customer_datails0 = pd.read_excel("C:/Users/patri/OneDrive/Documentos/Proyecto-EDA/data/raw/customer-details.xlsx", sheet_name=0)
df_customer_datails0.head(5)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [6]:
# leemos la segunda página del libro excel "customer-datails"
df_customer_datails1 = pd.read_excel("C:/Users/patri/OneDrive/Documentos/Proyecto-EDA/data/raw/customer-details.xlsx", sheet_name=1)
df_customer_datails1.head(5)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,82407,0,1,2013-10-07,29,ef81336c-e41a-46d0-8a30-5d4ac3b836be
1,1,24877,0,0,2013-04-21,32,50b224ac-84b4-42a7-aba9-3e1d1d620479
2,2,78839,1,0,2013-11-25,21,9cb15c53-b647-464a-add9-09cdae04897c
3,3,113859,1,1,2013-01-06,12,f8aaf334-949d-4943-a214-b64fe9c088b4
4,4,147317,0,0,2013-07-10,14,885fe85a-3718-4760-a32a-a57628cf7528

In [7]:
# leemos la tercera página del libro excel "customer-datails"
df_customer_datails2 = pd.read_excel("C:/Users/patri/OneDrive/Documentos/Proyecto-EDA/data/raw/customer-details.xlsx", sheet_name=2)
df_customer_datails2.head(5)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,168812,1,1,2014-06-10,27,4d6c811c-0f24-4a73-b374-2ebd1f80d46e
1,1,108615,2,1,2014-04-05,24,eef0f24f-cbdb-4c67-b371-09d7bc59695e
2,2,179041,0,2,2014-09-22,4,bbfdcedd-199d-4927-94bb-5dad051ff471
3,3,116639,2,2,2014-08-16,3,e8ebb67d-4ee1-4615-b701-eefe3af607eb
4,4,49537,0,1,2014-09-05,28,f7f79ace-0024-4505-a401-f340946f0942

----------------------

3. Unión de hojas de customer-details

In [8]:
# Unión de las 3 hojas en un mismo DataFrame
df_customer_datails = pd.concat([df_customer_datails0, df_customer_datails1, df_customer_datails2])
df_customer_datails.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [9]:
# Leemos las últimas 5 líneas
df_customer_datails.tail()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
14085,14085,156980,1,2,2014-05-17,7,5f432048-d515-4bb5-9c94-62db451f88d4
14086,14086,139820,0,0,2014-09-29,1,993bbbd6-4dbc-4a40-a408-f91f8462bee6
14087,14087,78470,2,2,2014-10-28,12,d6271666-319d-42c8-a741-cb22bf2c2093
14088,14088,144218,0,1,2014-07-01,9,f67fbfa8-6573-414d-a805-b26a2f1b1ceb
14089,14089,115155,0,2,2014-12-25,7,9727bc06-c11a-461a-a5bb-3d210467cc2a

In [10]:
# Para una mejor comprobación de la unión de las 3 hojas del libro excel, mostramos filas al azar 
df_customer_datails.sample(5)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
13098,13098,72749,1,2,2012-12-21,16,0e4ea0e4-2327-4c42-83e2-de907f0f537e
11704,11704,175447,2,0,2012-04-30,8,43dd6c70-30d8-47e1-b2c5-e2721f148576
10241,10241,39445,1,0,2012-05-19,3,706d7c75-9ae1-4e32-a049-e245e2f4d050
12426,12426,79208,1,2,2012-01-28,11,f5b2e863-3f03-41df-91a5-99e65714db06
3288,3288,82794,0,2,2013-08-20,20,37c3ac0a-0b43-4aaa-936e-8f4318cd2661

-------------------

4. Inspección inicial de bank-additional

In [11]:
df_bank_additional.shape

(43000, 24)

In [12]:
df_bank_additional.size

1032000

In [13]:
df_bank_additional.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  str
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: float64(7), int64(5), str(12)
memory usage: 7.9 MB

---------------------------

5. Limpieza y transformación de bank-additional

- Nulos

In [14]:
df_bank_additional.stb.missing()

                missing  total    percent
euribor3m          9256  43000  21.525581
default            8981  43000  20.886047
age                5120  43000  11.906977
education          1807  43000   4.202326
loan               1026  43000   2.386047
housing            1026  43000   2.386047
cons.price.idx      471  43000   1.095349
job                 345  43000   0.802326
date                248  43000   0.576744
marital              85  43000   0.197674
Unnamed: 0            0  43000   0.000000
contact               0  43000   0.000000
pdays                 0  43000   0.000000
previous              0  43000   0.000000
campaign              0  43000   0.000000
duration              0  43000   0.000000
emp.var.rate          0  43000   0.000000
poutcome              0  43000   0.000000
nr.employed           0  43000   0.000000
cons.conf.idx         0  43000   0.000000
y                     0  43000   0.000000
latitude              0  43000   0.000000
longitude             0  43000   0.000000
id_                   0  43000   0.000000

In [15]:
# Comprobación del % de nulos por columna (de mayor a menor)
(df_bank_additional.isna().mean() * 100).sort_values(ascending=False).head(15)

euribor3m         21.525581
default           20.886047
age               11.906977
education          4.202326
loan               2.386047
housing            2.386047
cons.price.idx     1.095349
job                0.802326
date               0.576744
marital            0.197674
Unnamed: 0         0.000000
contact            0.000000
pdays              0.000000
previous           0.000000
campaign           0.000000
dtype: float64

In [16]:
df_bank_additional["age_missing"] = df_bank_additional["age"].isna().astype(int)
df_bank_additional["euribor_missing"] = df_bank_additional["euribor3m"].isna().astype(int)

In [17]:
cols_cat_missing = ["default", "loan", "housing"]

for col in cols_cat_missing:
    df_bank_additional[col] = df_bank_additional[col].fillna("unknown")

# Las variables categóricas (`default`, `loan`, `housing`) presentan valores
# faltantes que se sustituyen por la categoría `"unknown"`, ya que representan
# información no disponible.

- Duplicados

In [18]:
# Duplicados totales y duplicados por id (si existe)
df_bank_additional.duplicated().sum(), df_bank_additional["id_"].duplicated().sum()

# No tenemos duplicados

(np.int64(0), np.int64(0))

- Columnas sobrantes

In [19]:
# quitar unnamed
df_bank_additional = df_bank_additional.drop(columns=[c for c in df_bank_additional.columns if c.lower().startswith("unnamed")], errors="ignore")
df_bank_additional.shape

(43000, 25)

- Conversión de datos

In [20]:
# Convertir columnas con coma decimal a numero
num_comma_cols = ["emp.var.rate", "cons.price.idx", "cons.conf.idx", "euribor3m", "nr.employed"]

for col in num_comma_cols:
    if col in df_bank_additional.columns:
        df_bank_additional[col] = (
            df_bank_additional[col].astype("string")
            .str.replace(",", ".", regex=False)
        )
        df_bank_additional[col] = pd.to_numeric(df_bank_additional[col], errors="coerce")

df_bank_additional[num_comma_cols].dtypes

emp.var.rate      Float64
cons.price.idx    Float64
cons.conf.idx     Float64
euribor3m         Float64
nr.employed       Float64
dtype: object

In [21]:
meses = {
    "enero": "01",
    "febrero": "02",
    "marzo": "03",
    "abril": "04",
    "mayo": "05",
    "junio": "06",
    "julio": "07",
    "agosto": "08",
    "septiembre": "09",
    "octubre": "10",
    "noviembre": "11",
    "diciembre": "12"
}
for mes, num in meses.items():
    df_bank_additional["date"] = df_bank_additional["date"].str.replace(mes, num)

In [22]:
df_bank_additional["date"] = pd.to_datetime(df_bank_additional["date"], dayfirst=True)
df_bank_additional["date"].head()

0   2019-08-02
1   2016-09-14
2   2019-02-15
3   2015-11-29
4   2017-01-29
Name: date, dtype: datetime64[us]

In [23]:
df_bank_additional["date"].dtype

dtype('<M8[us]')

In [24]:
# Limpiar columnas de categóricas
cat_cols = ["job", "marital", "education", "contact", "poutcome"]
# Quitamos espacios y minúsculas 
for col in cat_cols:
    df_bank_additional[col] = (
        df_bank_additional[col]
        .astype(str)
        .str.strip()      
        .str.lower()    
    )

In [25]:
# Sultición de los missing values en las columnas categóricas por "unknown"
cat_cols = ["job", "marital", "education", "contact", "poutcome"]
for col in cat_cols:
    df_bank_additional[col]= df_bank_additional[col].fillna("unknown")

In [26]:
# Comprobación de la sustituación 
df_bank_additional[cat_cols].isna().sum()

job          0
marital      0
education    0
contact      0
poutcome     0
dtype: int64

In [27]:
# Limpieza de la columna "y"
df_bank_additional["y"] = (
    df_bank_additional["y"]
    .astype(str)
    .str.strip()
    .str.lower()
)

In [28]:
# Sustitución de los valores de la columna "y" a binarios para un mejor análisis posterior 
df_bank_additional["y"] = df_bank_additional["y"].map({"yes": 1, "no": 0})

In [29]:
df_bank_additional["y"].value_counts()

y
0    38156
1     4844
Name: count, dtype: int64

In [30]:
df_bank_additional["cons.price.idx"] = df_bank_additional["cons.price.idx"].fillna(
    df_bank_additional["cons.price.idx"].median()
)

# La variable numérica `cons.price.idx` se imputa con la mediana para evitar
# perder registros y mantener la distribución de los datos.

- Imputar valores numericos

In [31]:
# Para "age"
df_bank_additional["age"] = df_bank_additional["age"].fillna(df_bank_additional["age"].median())

In [32]:
# Para "euribor3m"
df_bank_additional["euribor3m"] = df_bank_additional["euribor3m"].fillna(df_bank_additional["euribor3m"].median())

- Crear features de fecha

In [33]:
df_bank_additional["contact_year"] = df_bank_additional["date"].dt.year
df_bank_additional["contact_month"] = df_bank_additional["date"].dt.month

- Eliminación de fechas nulas

In [34]:

# Comprobación de cuántas fechas nulas hay
df_bank_additional["date"].isna().sum()

np.int64(248)

In [35]:
# Eliminación de fechas
df_bank_additional = df_bank_additional.dropna(subset=["date"])

In [36]:
# Comprobación 
df_bank_additional["date"].isna().sum()

np.int64(0)

In [37]:
# Crear día de la semana del contacto
df_bank_additional["contact_weekday"] = df_bank_additional["date"].dt.day_name()

- Creación de la variable "was_contacted_before"

In [38]:
df_bank_additional["was_contacted_before"] = (
    df_bank_additional["previous"]> 0
).astype(int)

In [39]:
# Comprobación 
df_bank_additional["was_contacted_before"].value_counts()

was_contacted_before
0    36883
1     5869
Name: count, dtype: int64

In [40]:
# Revisión de duplicados por id
df_bank_additional["id_"].duplicated().sum()

np.int64(0)

- Tratar "pdays" (999 significa que no se ha contactado)

In [41]:
df_bank_additional["pdays"].value_counts()
# Vemos que tenemos 41175 clientes con los que no hemos contactado

pdays
999    41175
3        454
6        425
4        121
9         67
2         63
7         62
12        61
10        55
5         49
13        38
11        30
1         26
15        26
14        22
8         20
0         15
16        13
17        10
18         7
22         4
19         3
21         2
25         1
26         1
27         1
20         1
Name: count, dtype: int64

In [42]:
# Sustituir 999 por "NaN"
df_bank_additional["pdays"] = df_bank_additional["pdays"].replace(999, "NaN")

In [43]:
# Comprobación
df_bank_additional["pdays"].describe()

count     42752
unique       27
top         NaN
freq      41175
Name: pdays, dtype: object

In [44]:
df_bank_additional.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,date,latitude,longitude,id_,age_missing,euribor_missing,contact_year,contact_month,contact_weekday,was_contacted_before
0,38.0,housemaid,married,basic.4y,0.0,0.0,0.0,telephone,261,1,...,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,1,0,2019.0,8.0,Friday,0
1,57.0,services,married,high.school,unknown,0.0,0.0,telephone,149,1,...,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,0,1,2016.0,9.0,Wednesday,0
2,37.0,services,married,high.school,0.0,1.0,0.0,telephone,226,1,...,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,0,0,2019.0,2.0,Friday,0
3,40.0,admin.,married,basic.6y,0.0,0.0,0.0,telephone,151,1,...,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,0,1,2015.0,11.0,Sunday,0
4,56.0,services,married,high.school,0.0,0.0,1.0,telephone,307,1,...,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,0,1,2017.0,1.0,Sunday,0

-----------------------------------------------------------

6. Inspección inicial de customer-details

In [45]:
df_customer_datails.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [46]:
df_customer_datails.shape

(43170, 7)

In [47]:
df_customer_datails.size

302190

In [48]:
df_customer_datails.info()

<class 'pandas.DataFrame'>
Index: 43170 entries, 0 to 14089
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[us]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 2.6 MB

----------------

7. Limpieza y transformación de customer-details

- nulos

In [49]:
df_customer_datails.stb.missing()

                   missing  total  percent
Unnamed: 0               0  43170      0.0
Income                   0  43170      0.0
Kidhome                  0  43170      0.0
Teenhome                 0  43170      0.0
Dt_Customer              0  43170      0.0
NumWebVisitsMonth        0  43170      0.0
ID                       0  43170      0.0

- Columnas inmencesarias

In [50]:
# quitar unnamed
df_customer_datails = df_customer_datails.drop(columns=[c for c in df_customer_datails.columns if c.lower().startswith("unnamed")], errors="ignore")
df_customer_datails.shape

(43170, 6)

- Duplicados

In [51]:
# Duplicados 
df_customer_datails["ID"].duplicated().sum()

# No hay dumplicados

np.int64(0)

- Transformación

In [52]:
# Revisión de la distribución de income
df_customer_datails["Income"].describe()

# Para ver en que rango de valores nos encontramos

count     43170.000000
mean      93227.389622
std       50498.181989
min        5841.000000
25%       49608.000000
50%       93009.500000
75%      136740.500000
max      180802.000000
Name: Income, dtype: float64

In [53]:
# Valores de los hijos del cliente
df_customer_datails["Kidhome"].value_counts()

Kidhome
2    14475
1    14425
0    14270
Name: count, dtype: int64

In [54]:
df_customer_datails["Teenhome"].value_counts()

Teenhome
1    14425
0    14402
2    14343
Name: count, dtype: int64

In [55]:
# Crear feature de tamaño de familia
df_customer_datails["Family_size"]= (
    df_customer_datails["Kidhome"] +
    df_customer_datails["Teenhome"]
)

# Para saber cuántos hijos tiene cada cliente

In [56]:
# Creamos features binarias para el posterior análisis 1 = tiene hijos, 0 = a no tiene hijos 
df_customer_datails["Has_kid"] = (df_customer_datails["Kidhome"]> 0 ).astype(int)

In [57]:
df_customer_datails["Has_teens"] = (df_customer_datails["Teenhome"]> 0 ).astype(int)

In [58]:
# Extraemos información de la fecha del cliente
# DT_Customer es la fecha en la que el cliente se registró

# Año de registro 
df_customer_datails["Customer_year"] = (df_customer_datails["Dt_Customer"]).dt.year

In [59]:
# Mes de registro
df_customer_datails["Customer_month"] = (df_customer_datails["Dt_Customer"]).dt.month

In [60]:
# Validar rango de fechas
df_customer_datails["Dt_Customer"].min(), df_customer_datails["Dt_Customer"].max()

(Timestamp('2012-01-01 00:00:00'), Timestamp('2014-12-31 00:00:00'))

In [61]:
# Revisar visitas web
df_customer_datails["NumWebVisitsMonth"].describe()

count    43170.000000
mean        16.591290
std          9.241769
min          1.000000
25%          9.000000
50%         17.000000
75%         25.000000
max         32.000000
Name: NumWebVisitsMonth, dtype: float64

In [62]:
# Creación de la variable de antigüedad del cliente por años 
df_customer_datails["Customer_tenure_years"] = ((
    pd.Timestamp.today() - df_customer_datails["Dt_Customer"]
).dt.days / 365
).round(0)

In [63]:
# Comprobación final del dataset
df_customer_datails.info()

<class 'pandas.DataFrame'>
Index: 43170 entries, 0 to 14089
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Income                 43170 non-null  int64
 1   Kidhome                43170 non-null  int64
 2   Teenhome               43170 non-null  int64
 3   Dt_Customer            43170 non-null  datetime64[us]
 4   NumWebVisitsMonth      43170 non-null  int64
 5   ID                     43170 non-null  str
 6   Family_size            43170 non-null  int64
 7   Has_kid                43170 non-null  int64
 8   Has_teens              43170 non-null  int64
 9   Customer_year          43170 non-null  int32
 10  Customer_month         43170 non-null  int32
 11  Customer_tenure_years  43170 non-null  float64
dtypes: datetime64[us](1), float64(1), int32(2), int64(7), str(1)
memory usage: 4.0 MB

In [64]:
df_customer_datails.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,Family_size,Has_kid,Has_teens,Customer_year,Customer_month,Customer_tenure_years
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,1,1,0,2012,4,14.0
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,2,1,1,2012,12,13.0
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b,2,1,1,2012,2,14.0
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e,3,1,1,2012,12,13.0
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,3,1,1,2012,6,14.0

--------------------

8. Guardado del dataset limpio

In [65]:
df_bank_additional["id_"].isin(df_customer_datails["ID"]).mean()

np.float64(1.0)

In [66]:
# Merge de los dataset por id 
df_bank_marketing = df_bank_additional.merge(
    df_customer_datails, 
    left_on="id_", 
    right_on= "ID",
    how= "left"
)

In [67]:
df_bank_marketing = df_bank_marketing.drop(columns=["ID"])

Tras realizar el merge entre `bank_additional` y `customer_details`,
se elimina la columna `ID` duplicada para mantener un único identificador (`id_`).

In [68]:
# Tamaño del dataset final
df_bank_marketing.shape

(42752, 40)

In [69]:
df_bank_marketing.stb.missing()

                       missing  total  percent
age                          0  42752      0.0
job                          0  42752      0.0
marital                      0  42752      0.0
education                    0  42752      0.0
default                      0  42752      0.0
housing                      0  42752      0.0
loan                         0  42752      0.0
contact                      0  42752      0.0
duration                     0  42752      0.0
campaign                     0  42752      0.0
pdays                        0  42752      0.0
previous                     0  42752      0.0
poutcome                     0  42752      0.0
emp.var.rate                 0  42752      0.0
cons.price.idx               0  42752      0.0
cons.conf.idx                0  42752      0.0
euribor3m                    0  42752      0.0
nr.employed                  0  42752      0.0
y                            0  42752      0.0
date                         0  42752      0.0
latitude                     0  42752      0.0
longitude                    0  42752      0.0
id_                          0  42752      0.0
age_missing                  0  42752      0.0
euribor_missing              0  42752      0.0
contact_year                 0  42752      0.0
contact_month                0  42752      0.0
contact_weekday              0  42752      0.0
was_contacted_before         0  42752      0.0
Income                       0  42752      0.0
Kidhome                      0  42752      0.0
Teenhome                     0  42752      0.0
Dt_Customer                  0  42752      0.0
NumWebVisitsMonth            0  42752      0.0
Family_size                  0  42752      0.0
Has_kid                      0  42752      0.0
Has_teens                    0  42752      0.0
Customer_year                0  42752      0.0
Customer_month               0  42752      0.0
Customer_tenure_years        0  42752      0.0

In [70]:
# Qué porcentaje no hay cliente 
df_bank_marketing["Income"].isna().mean()

np.float64(0.0)

In [71]:
# Si hay duplicados de filas 
df_bank_marketing["id_"].duplicated().sum()

np.int64(0)

In [72]:
# Creación de la variable "tenure_at_contact"
# Para saber cuánto tiempo llevaba el cliente cuándo recibió la llamada 
df_bank_marketing["tenure_at_contact_days"] = ((
    df_bank_marketing["date"] - df_bank_marketing["Dt_Customer"]
).dt.days /365 
).round(0)

In [75]:
df_bank_marketing.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,Teenhome,Dt_Customer,NumWebVisitsMonth,Family_size,Has_kid,Has_teens,Customer_year,Customer_month,Customer_tenure_years,tenure_at_contact_days
0,38.0,housemaid,married,basic.4y,0.0,0.0,0.0,telephone,261,1,...,0,2012-04-04,29,1,1,0,2012,4,14.0,7.0
1,57.0,services,married,high.school,unknown,0.0,0.0,telephone,149,1,...,1,2012-12-30,7,2,1,1,2012,12,13.0,4.0
2,37.0,services,married,high.school,0.0,1.0,0.0,telephone,226,1,...,1,2012-02-02,5,2,1,1,2012,2,14.0,7.0
3,40.0,admin.,married,basic.6y,0.0,0.0,0.0,telephone,151,1,...,2,2012-12-21,29,3,1,1,2012,12,13.0,3.0
4,56.0,services,married,high.school,0.0,0.0,1.0,telephone,307,1,...,2,2012-06-20,20,3,1,1,2012,6,14.0,5.0

In [76]:
df_bank_marketing.tail()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,Teenhome,Dt_Customer,NumWebVisitsMonth,Family_size,Has_kid,Has_teens,Customer_year,Customer_month,Customer_tenure_years,tenure_at_contact_days
42747,38.0,admin.,married,university.degree,0.0,0.0,0.0,cellular,618,2,...,2,2014-03-08,22,2,0,1,2014,3,12.0,2.0
42748,34.0,technician,married,professional.course,0.0,1.0,1.0,cellular,42,7,...,2,2014-03-11,26,2,0,1,2014,3,12.0,4.0
42749,38.0,blue-collar,single,basic.6y,0.0,1.0,0.0,cellular,391,2,...,2,2014-09-18,31,4,1,1,2014,9,11.0,2.0
42750,38.0,admin.,married,university.degree,unknown,0.0,0.0,cellular,674,3,...,2,2014-05-17,7,3,1,1,2014,5,12.0,5.0
42751,38.0,unemployed,single,university.degree,0.0,0.0,1.0,cellular,104,2,...,0,2014-09-29,1,0,0,0,2014,9,11.0,5.0

In [80]:
df_bank_marketing.to_csv("C:/Users/patri/OneDrive/Documentos/Proyecto-EDA/data/processed/bank_marketing.csv", index= False)